# Generated by Django 2.2.8 on 2020-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
